### PR TITLE
Talk to pod

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
I rebased this on #1, seems to work!

**Review by mrakitin — COMMENTED** [review]
Is `package-lock.json` expected here?

**Comment by tacaswell** [comment]
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5 SO (and the docs https://github.com/npm/cli/blob/release-6.14.7/docs/content/configuring-npm/package-lock-json.md) claim yes.

**Review by cryos — APPROVED** [review]

**Comment by cryos** [comment]
I just realized after approving that this works for pods, but not local development. I can fix that up in a follow up commit, and maybe improve the calls to the API a little too.

**Comment by tacaswell** [comment]
I guess the fix is to on the server side to add at `/api/` or `/db/` to the routes in the server and then adjust the nginx to duplicate that part of the address?

**Comment by cryos** [comment]
I think we can just adjust the proxy in the client to add the prefix to the server it is already proxying, I can take a look.

**Comment by cryos** [comment]
Do you want to rewrite/remove the WIP commit? I always used WIP (work in progress) for commits that should never be merged. Maybe you use a different convention? I think the client code needs some flexibility to set an API prefix in one spot, and we should set the default to something sensible. I can do that in a follow up commit and let the development without pods be broken briefly.

**Comment by tacaswell** [comment]
Feel free to squash / rewrite / discard my commits here, My main goal was to externalize what was running on my machine!

**Pull request merged**
